; SMALL M/C MONITOR FOR THE GS32KZ80 BY PHIL GREEN LOCKDOWN 2021
; iN GS NASCOM BASIC, FROM 1.DB8 THERE ARE 583 (DECIMAL) BYTES FREE
; COMMANDS - MODIFY, DISPLAY, EXEC, INTEL UPLOADER, HEX ARITHMETIC, INTELLIGENT COPY
; G=GO GXXXX, D=DISPLAY DXXXX, M=MODIFY MXXXX, I=INTELHEXLOADER, B=BASIC, C=COPY, A=ARITH
;
; Mods 17/03/23 
; Previously a G command was committed. Can now abort with a '.'
; Monitor start address pushed onto stack before "G"oto allow RET to monitor.
; Briefer help cmd "?"  In basic change version to 4.7m for monitor
;
	.ORG	1DC0H

MON:	CALL	ILPRINT
	.DB	13,10,"Mon >",0

; 	<A>RITH <B>ASIC <C>OPY <D>ISPLAY <G>OTO <I>NTEL <M>ODIFY

	CALL	INCHE
	CP	'G'	; GOTO USER PROGRAM
	JR	Z,GOCMD
	CP	'D'	; DISPLAY
	JR	Z,HEXDIS
	CP	'M'	; MODIFY?
	JR	Z,MODCMD
	CP	'I'	; INTEL LOADER
	JP	Z,INTEL
	CP	'B'	; BASIC?
	JP	Z,0
	CP	'C'	; COPY?
	JP	Z,ICOPY
	CP	'A'	; ARITHMETIC?
	JP	Z,ARITH
	CP	'?'
	JP	Z,HELP

; OTHER COMMAND CHARACTER TESTS...

	JR	MON

GOCMD:	CALL	HEXIN	; GET ADDRESS
	CP	'.'
	JR	Z,MON	; ALLOW ABORT
	LD	DE,MON
	PUSH	DE	; FOR 'RET' TO MONITOR
	JP	(HL)	; AND GO

MODCMD:	CALL	HEXIN			; GET MODIFY ADDR
	LD	D,H			; SAVE ADDR IN DE
	LD	E,L

MODCM2:	LD	H,D			; RESTORE ADDR FROM DE
	LD	L,E
	CALL	NEWLIN
	CALL	HLHEX			; PRINT ADDRESS
	CALL	SPACE			; SPACE
	LD	A,(HL)			; GET EXISTING BYTE
	LD	D,H			; SAVE ADDR IN DE
	LD	E,L
	CALL	B2HEX			; PRINT IT
	CALL	SPACE			; TIDY UP LATER MAYBE " >"
	CALL	HEXIN			; GET NEW BYTE VALUE INTO L
	CP	'.'			; A='.' MEANS STOP
	JR	Z,MON
	LD	A,C
	OR	A			; C=0 MEANS SKIP
	JR	Z,MODCM3
	LD	A,L			; GET NEW DATA
	LD	(DE),A			; PLACE NEW DATA
MODCM3:	INC	DE
	JR	MODCM2			; AND LOOP TILL '.'

HEXDIS:	CALL	HEXIN			; GET START ADDR
	CALL	NEWLIN
	LD	C,8			; ROWS TO SHOW
ROWLP:	PUSH	HL
	CALL	HLHEX			; SHOW THE ADDRESS
	CALL	SPACE
	POP	HL
	PUSH	HL			; SAVE ADDR FOR ASCII BIT
	LD	B,16			; BYTES PER ROW
COL_LOOP:
	LD	A,(HL)			; GET THE BYTE
	CALL	B2HEX
	LD	A,' '
	RST	08H			; LEAVE A SPACE
	INC	HL			; CONTINUE TO NEXT BYTE
	DJNZ	COL_LOOP		; CONTINUE TO NEXT COLUMN
	CALL	SPACE
	POP	HL			; NOW GO OVER THE LINE AGAIN IN ASCII
	LD	B,16			; BYTES PER ROW
ASCII_LOOP:
	LD	A,(HL)			; GET THE BYTE
	CP	7EH
	JR	C,LT7E			; LESS THAN 7E
	LD	A,'.'			; OVER 7EH = DOT
LT7E:	CP	' '
	JR	NC,LT20			; LESS THAN 20?
	LD	A,'.'			; UNDER 20H = DOT
LT20:	RST	08H			; PRINT A IN ASCII
	INC	HL			; CONTINUE TO NEXT CHAR
	DJNZ	ASCII_LOOP		; CONTINUE TO NEXT COLUMN
	CALL	NEWLIN			; NEXT LINE
	DEC	C
	JR	NZ,ROWLP		; CONTINUE TO NEXT ROW
	CALL	NEWLIN
	JP	MON

; PRINT HL IN 4-DIGIT HEX	
HLHEX:	LD	A,H
	CALL	B2HEX
	LD	A,L
;	FALL THROUGH...
; PRINT A IN HEX
B2HEX:	PUSH	AF
	RRA
	RRA
	RRA
	RRA
	CALL	B2HEX1
	POP	AF
B2HEX1:	AND	0FH
	ADD	A,30H
	CP	'9'+1
	JR	C,JCRT
	ADD	A,7
JCRT:	RST	08H
	RET

; INTEL HEX READER
INTEL:	CALL 	INCH
	AND	7FH	 ; SCRAP PARITY
	CP	':'	 ; WAIT FOR START
	JR	NZ,INTEL
	CALL	PHEX	; GET RECORD LENGTH
	LD	B,E	; B IS CHECKSUM
	OR	A	; ZERO LENGTH MEANS EOF
	JP	Z,ENDFL
	LD	C,A	; SAVE LENGTH IN C
	CALL	PHEX	; GET LOAD ADDRESS
	LD	H,A	 
	CALL	PHEX	
	LD	L,A	 
	CALL	PHEX	; DISCARD RECORD TYPE
ILOOP:	CALL	PHEX	; GET DATA
	LD	(HL),A	; STORE TO MEM
	CP	(HL)	; SEE IF STORED
	JR	NZ,NOSTOR
	INC	HL	
	DEC	C	 
	JR	NZ,ILOOP; DO RECORD LENGTH
	CALL	CHECK	
	JP	INTEL	; NEXT RECORD
;
HXERR:	CALL	ILPRINT
	.DB	13,10,"~Hex!",13,10,0
	JR	MONJ
NOSTOR:	CALL	ILPRINT
	.DB	13,10,"ROM?",13,10,0
MONJ:	JP	MON	 
;
PHEX:	CALL	INHEX	 ; READ UPPER
	RLCA		
	RLCA		
	RLCA		
	RLCA		
	LD	E,A	 
	CALL	INHEX	 
	OR	E	 
	LD	E,A	 ; SAVE
	ADD	A,B	 ; CHECKSUM
	LD	B,A	 
	LD	A,E	 ; RETREIVE
	RET		 
;
INHEX:	CALL	INCH
	AND	7FH	 ; STRIP PARITY
	SUB	30H	 
	JR	C,HXERR 
	CP	23	
	JR	NC,HXERR
	CP	10	
	RET	C	 ; IF 0-9
	SUB	7	 
	CP	10	
	JR	C,HXERR	; BETWEEN 9-A
	RET		; A-F OK

CHECK:	CALL	PHEX	
	XOR	A	 
	ADD	A,B	 
	JR	Z,CSOK	 ; ZERO = OK
	CALL	ILPRINT
	.DB	13,10,"Csum!",13,10,0	
	JR	MONJ
CSOK:	LD	A,'.'
	RST	08H
	RET

ENDFL:	CALL 	INCH
	CP	0DH	 ; WAIT FOR LAST CR
	JR	NZ,ENDFL
	JR	MONJ

	; ARITHMETIC COMMAND - SUM, DIFFERENCE, RELATIVE JUMP OFFSET
ARITH:	CALL	HEXINL
	EX	DE,HL	; DE=ARG1
	CALL	HEXINL	; HL=ARG2
	EX	DE,HL	; HL=ARG1, DE=ARG2
	CALL	ILPRINT
	.DB	13,10,"SUM  DIFF RJ",13,10,0

	PUSH	HL	; SAVE ARG1
	; SUM
	ADD	HL,DE	; RESULT IN HL
	CALL	HLHEX
	CALL	SPACE
	POP	HL	; HL=ARG1, DE=ARG2

	; DIFFERENCE
	PUSH	HL
	OR	A
	SBC	HL,DE	; HL = ARG1 - ARG2
	CALL	HLHEX
	CALL	SPACE
	POP	HL	; HL=ARG1, DE=ARG2

	; OFFSET
	EX	DE,HL	; DE=ARG1, HL=ARG2
	OR	A
	SBC	HL,DE
	DEC	HL
	DEC	HL
	LD	A,H
	RLC	L
	ADC	A,0
	JR	Z,AOK
	; NO GOOD SO ??
ANG:	CALL	ILPRINT
	.DB	"??",13,10,0
MONJA	JP	MON
	; OUTPUT OFFSET
AOK:	LD	A,L
	RRCA
A7:	CALL	B2HEX
	JR	MONJA

	; INTELLIGENT COPY COMMAND
	; IF ARG1 GE ARG2, GOTO 
	;   LDIR COPY
ICOPY:	CALL	HEXINL	; ARG1 'FROM'
	PUSH	HL
	CALL	HEXINL	; ARG2 'TO'
	PUSH	HL
	CALL	HEXINL	; ARG3 LENGTH
	PUSH	HL
	POP	BC	; BC=LENGTH
	POP	DE	; DE=DESTINATION
	POP	HL	; HL=FROM
	OR	A
	SBC	HL,DE
	ADD	HL,DE
	JR	NC,COPY
	; SET TO END NOT START
	DEC	BC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	ADD	HL,BC
	INC	BC
	LDDR
	JR	MONJC
	
	; COPY COMMAND
COPY:	LDIR
MONJC:	JP	MON

; BUILD ADDRESS OR DATA FROM UP TO 4 KEYSTROKES, EXIT ON (CR) WITH RESULT IN HL
; C IS NZ IF THERE WAS INPUT, ZERO IF BARE C/R NO DATA
HEXINL:	CALL	NEWLIN	; TIDYIER
HEXIN:	LD	HL,0	; CLEAR RESULT
	LD	C,0	; FLAG EMPTY INPUT
NIBBLE:	CALL	INCHE
	CP	0DH	; C/R?
	RET	Z	; RETURN WITH A  = C/R
	CP	'.'
	RET	Z	; RETURN WITH A  = '.'
	CP	' '
	RET	Z	; RETURN WITH A  = ' '
	CP	'G'	; SET CY IF >F
	JR	NC,NIBBLE
	SUB	'0'	; SET CY IF < "0"
	JR	C,NIBBLE
	CP	10H	; IF 0-9 OK
	JR	C,DIGIT	; WAS NC?
	SUB	7	; ELSE ADJUST
DIGIT:	ADD	HL,HL	; SHIFT LEFT BY 1 NIBBLE
	ADD	HL,HL	; SHIFT LEFT BY 1 NIBBLE
	ADD	HL,HL	; SHIFT LEFT BY 1 NIBBLE
	ADD	HL,HL	; SHIFT LEFT BY 1 NIBBLE
	ADD	A,L
	LD	L,A
	INC	C
	JR	NIBBLE	; LOOP TILL C/R

HELP:	CALL	ILPRINT
	.DB	13,"Ar/Ba/Cp/Ds/Go/In/Mo - Phil_G 2021",13,10,0
	JP	MON

; PRINT THE FOLLOWING INLINE STRING, TERMINATED BY 00
ILPRINT:
	EX	(SP),HL
ILP1:	LD	A,(HL)
	INC	HL
	OR	A
	JR	Z,ILP2
	RST	08H
	JR	ILP1
ILP2:	EX	(SP),HL
	RET

SPACE:	LD	A,' '
	RST	08H
	RET

NEWLIN:	LD	A,0DH
	RST	08H
	LD	A,0AH
	RST	08H
	RET

INCHE:	RST	10H	; FALL THROUGH TO ECHO CHARACTER
OUTCH:	RST	08H	; PRINT ASCII CHAR IN A, PRESERVES ALL REGS.
	RET

INCH:	RST	10H	; INPUT WITHOUT ECHO
	RET

	.END


